publish:
  whoami: asf-site

github:
  labels:
    - apache
    - solr
    - website
    - pelican
  enabled_merge_buttons:
    squash: true
    merge:  true
    rebase: false
  protected_branches:
    main
    production
