#!/usr/bin/env python3
"""Regenerate solr-dependency-versions.json from a real syft SBOM scan of each
tracked Solr release's actual binary distribution, instead of resolving a
declared Maven dependency graph. A declared graph misses anything Solr bundles
at packaging time (e.g. its own Jetty server) and can conflate a tracked
artifact with an unrelated same-named dependency pulled in by some other,
optional module -- syft instead reads the real jars on disk.

Usage:
    python3 plugins/vex/regenerate_dependency_mappings.py [VERSION ...]

With no arguments, every version in solr-versions.txt is (re)scanned, which
downloads and unpacks each release's full binary distribution (tens to a few
hundred MB each) -- expect a full run to take a long time and a lot of
bandwidth, since archive.apache.org (the only host with the complete release
history) serves archived releases slowly. Pass one or more specific versions
(e.g. just-released ones) to only refresh those. The full distribution is always
used, so dependencies that only live in optional modules (Hadoop, Tika, etc) are
covered.

Before scanning, the script refreshes solr-versions.txt by discovering released
versions from the Apache archive (archive.apache.org/dist/solr/solr/ -- the 9.0+
standalone releases, where every new release lands) and unioning them into the
file. Existing entries (including the pre-9.0 history, which lives under a
different, unchanging archive path) are never dropped, so discovery can only add
newly-released versions, never silently lose old ones. Pass --no-discover to skip
this and use the committed list as-is. At the end, the script also checks that
every Solr version present in solr-dependency-versions.json is listed in
solr-versions.txt (a drift guard, since expand_versions only enumerates versions
that appear there).

Only already-tracked dependencies (existing keys in solr-dependency-versions.json)
are touched, and only to fill in a missing (dependency, Solr version) entry --
an existing value is never overwritten. A resolved value that disagrees with
what's on file is reported as a conflict for a human to look into rather than
applied. Newly-seen third-party dependencies that aren't tracked yet are also
reported, for a human to decide whether to start tracking them.
"""
import argparse
import json
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

VEX_DIR = Path(__file__).resolve().parent
REPO_ROOT = VEX_DIR.parent.parent
VERSIONS_FILE = VEX_DIR / 'solr-versions.txt'
DEP_VERSIONS_FILE = VEX_DIR / 'solr-dependency-versions.json'
SYFT_IMAGE = 'anchore/syft:latest'

# Directory listing of the standalone-repo releases (Solr 9.0+). Every new
# release lands here, so discovering from it keeps solr-versions.txt current
# without a manual edit. The pre-9.0 history (a different, now-frozen archive
# path) is preserved by unioning with the committed file rather than re-scraped.
RELEASES_INDEX_URL = 'https://archive.apache.org/dist/solr/solr/'
# A version directory entry in that listing, e.g. href="9.10.0/". Requires the
# '/' immediately after the version so pre-release dirs (e.g. 9.0.0-RC1/) and
# non-version entries (KEYS, maven-metadata.xml) are excluded.
_VERSION_DIR_RE = re.compile(r'href="(\d+\.\d+(?:\.\d+)?)/"')

# Header prepended to a (re)generated solr-versions.txt.
VERSIONS_HEADER = """\
# Authoritative list of released Apache Solr versions, one per line.
#
# Used by the vex plugin (plugins/vex/vex.py, expand_versions) to expand the
# free-form `versions` ranges in content/solr/vex/*.md into concrete per-version
# purls in solr.openvex.json.
#
# Generated by plugins/vex/regenerate_dependency_mappings.py: it discovers 9.0+
# releases from archive.apache.org and unions them into this list (existing
# entries, including the pre-9.0 history, are never dropped). Re-run that script
# to refresh; hand-edits are fine too but will be re-sorted on the next run.
"""

# First-party groups: never worth tracking as a "third-party dependency".
EXCLUDED_GROUPS = {'org.apache.solr', 'org.apache.lucene'}


def _version_key(v):
    """Sort key: split a version string into a tuple of its integer parts."""
    return tuple(int(p) for p in re.findall(r'\d+', v))


def read_versions_file():
    """The released Solr versions listed in solr-versions.txt (comments/blank
    lines skipped)."""
    return [ln.strip() for ln in VERSIONS_FILE.read_text().splitlines()
            if ln.strip() and not ln.strip().startswith('#')]


def write_versions_file(versions):
    """Rewrite solr-versions.txt with the standard header and the given versions,
    de-duplicated and version-sorted, one per line."""
    body = '\n'.join(sorted(set(versions), key=_version_key))
    VERSIONS_FILE.write_text(VERSIONS_HEADER + body + '\n')


def discover_released_versions():
    """Discover released Solr version numbers from the Apache archive listing
    (the same host the tarballs come from). Returns a set of version strings, or
    None if the listing couldn't be fetched (so callers keep the existing file)."""
    try:
        with urllib.request.urlopen(RELEASES_INDEX_URL, timeout=60) as resp:
            html = resp.read().decode('utf-8', 'replace')
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as e:
        print(f'  could not fetch {RELEASES_INDEX_URL}: {e}', file=sys.stderr)
        return None
    return set(_VERSION_DIR_RE.findall(html))

# Candidate (base URL, filename) templates to try, in order, covering Solr's
# release-hosting history: the current standalone repo (9.0+), the older
# combined Lucene/Solr repo (~3.1-8.x), and that repo's older "apache-solr-"
# filename prefix (pre ~4.3-ish). The first template that downloads
# successfully is used.
URL_TEMPLATES = [
    'https://archive.apache.org/dist/solr/solr/{v}/solr-{v}.tgz',
    'https://archive.apache.org/dist/lucene/solr/{v}/solr-{v}.tgz',
    'https://archive.apache.org/dist/lucene/solr/{v}/apache-solr-{v}.tgz',
]


def download_distribution(version, dest):
    """Download the first resolvable release tarball for `version` into `dest`.
    Returns True on success, False if no URL template resolved."""
    for template in URL_TEMPLATES:
        url = template.format(v=version)
        try:
            with urllib.request.urlopen(url, timeout=60) as resp, open(dest, 'wb') as out:
                shutil.copyfileobj(resp, out)
            return True
        except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError):
            dest.unlink(missing_ok=True)
            continue
    return False


def run_syft(extracted_dir):
    """Run syft against the extracted distribution directory, returning the
    parsed CycloneDX JSON document, or None on failure."""
    try:
        result = subprocess.run(
            ['docker', 'run', '--rm', '-v', f'{extracted_dir}:/work',
             SYFT_IMAGE, '/work', '-o', 'cyclonedx-json'],
            capture_output=True, text=True, timeout=300,
        )
    except FileNotFoundError:
        sys.exit('ERROR: docker is required to run syft (see README.md for setup).')
    if result.returncode != 0 or not result.stdout.strip():
        return None
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


PURL_RE = re.compile(r'^pkg:maven/([^/]+)/([^@]+)@([^?]+)')


def _is_standalone_jar(component):
    """True if syft found this package as its own jar file on disk, rather than
    shaded/embedded inside another archive.

    syft records a `syft:metadata:virtualPath` for each component. For a
    standalone jar it is just the file path (e.g. `/.../commons-lang3-3.15.0.jar`),
    but for a package discovered *inside* another archive it appends
    archive-nesting separators (e.g.
    `/.../hadoop-shaded-guava-1.2.0.jar:com.google.guava:guava`). We only want the
    dependency jars Solr actually ships as files -- not the older copies that
    Hadoop's `hadoop-shaded-*` bundles (and similar fat jars) embed -- so we treat
    a ':' in the virtualPath as "nested" and skip it. If the property is absent
    (older syft), we default to keeping the component rather than over-filtering.
    """
    props = {p.get('name'): p.get('value') for p in component.get('properties', [])}
    vpath = props.get('syft:metadata:virtualPath', '')
    return ':' not in vpath


def iter_maven_packages(sbom):
    """Yield (group, artifact, version) for every Maven-purl component in a syft
    CycloneDX SBOM that syft found as a standalone jar (see _is_standalone_jar --
    packages shaded inside another archive are skipped)."""
    for component in sbom.get('components', []):
        m = PURL_RE.match(component.get('purl', ''))
        if m and _is_standalone_jar(component):
            yield m.groups()


def scan_version(version, work_dir):
    """Download, extract, and syft-scan `version`'s binary distribution under
    `work_dir`. Returns the parsed CycloneDX SBOM, or None if the release
    couldn't be downloaded, extracted, or scanned."""
    tarball = work_dir / 'dist.tgz'
    if not download_distribution(version, tarball):
        print(f'  no release tarball found for {version}, skipping', file=sys.stderr)
        return None
    extract_dir = work_dir / 'extracted'
    extract_dir.mkdir()
    try:
        with tarfile.open(tarball) as tf:
            try:
                tf.extractall(extract_dir, filter='data')
            except TypeError:
                tf.extractall(extract_dir)  # Python < 3.12 has no `filter` kwarg
    except tarfile.TarError as e:
        print(f'  failed to extract {version}: {e}', file=sys.stderr)
        return None
    finally:
        tarball.unlink(missing_ok=True)  # reclaim disk before/while syft runs
    sbom = run_syft(extract_dir)
    if sbom is None:
        print(f'  syft scan failed for {version}', file=sys.stderr)
    return sbom


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('versions', nargs='*',
                         help='Specific Solr versions to refresh (default: all)')
    parser.add_argument('--verbose', action='store_true',
                         help='List every untracked dependency seen, not just the count')
    parser.add_argument('--no-discover', action='store_true',
                         help="Don't refresh solr-versions.txt from the Apache archive first; "
                              'use the committed list as-is.')
    args = parser.parse_args()

    all_versions = read_versions_file()
    if not args.no_discover:
        print('Refreshing solr-versions.txt from archive.apache.org...', file=sys.stderr)
        discovered = discover_released_versions()
        if discovered is None:
            print(f'  WARNING: discovery failed (network?); keeping {VERSIONS_FILE.name} '
                  'unchanged.', file=sys.stderr)
        else:
            merged = set(all_versions) | discovered
            new = sorted(merged - set(all_versions), key=_version_key)
            write_versions_file(merged)  # normalize header + sort, even if unchanged
            if new:
                print(f'  added {len(new)} newly-released version(s): {", ".join(new)}',
                      file=sys.stderr)
            else:
                print(f'  already current ({len(all_versions)} versions).', file=sys.stderr)
            all_versions = sorted(merged, key=_version_key)
    versions = args.versions or all_versions
    unknown = sorted(set(versions) - set(all_versions))
    if unknown:
        sys.exit(f'Unknown Solr version(s), not in {VERSIONS_FILE.name}: {", ".join(unknown)}')

    dep_versions = json.loads(DEP_VERSIONS_FILE.read_text())
    tracked = set(dep_versions)
    new_candidates = {}
    conflicts = []
    skipped = []
    added = 0

    for i, version in enumerate(versions, 1):
        print(f'[{i}/{len(versions)}] Solr {version}...', file=sys.stderr)
        with tempfile.TemporaryDirectory() as tmp:
            sbom = scan_version(version, Path(tmp))
        if sbom is None:
            skipped.append(version)
            continue

        found_this_version = {}
        for group, artifact, dep_version in iter_maven_packages(sbom):
            key = f'{group}:{artifact}'
            if key in tracked:
                found_this_version.setdefault(key, dep_version)
            elif group not in EXCLUDED_GROUPS:
                new_candidates.setdefault(key, set()).add(version)

        # Only fill genuine gaps -- never overwrite an existing value. A
        # resolved value that disagrees with what's already on file is
        # surfaced as a conflict for a human to look into, never applied
        # automatically.
        for key, dep_version in found_this_version.items():
            existing = dep_versions.setdefault(key, {})
            if version not in existing:
                existing[version] = dep_version
                added += 1
            elif existing[version] != dep_version:
                conflicts.append((key, version, existing[version], dep_version))

        DEP_VERSIONS_FILE.write_text(json.dumps(dep_versions, indent=2) + '\n')

    print(f'\nUpdated {DEP_VERSIONS_FILE.relative_to(REPO_ROOT)}: filled {added} missing '
          f'(dependency, version) entries.', file=sys.stderr)

    if skipped:
        print(f'\n{len(skipped)} version(s) skipped (no release tarball found, or '
              f'extraction/scan failed): {", ".join(skipped)}', file=sys.stderr)

    if conflicts:
        print(f'\n{len(conflicts)} resolved value(s) disagree with what is already on file '
              f'-- left UNCHANGED, please review by hand:', file=sys.stderr)
        for key, version, existing_value, resolved_value in conflicts:
            print(f'  {key} @ {version}: on file = {existing_value!r}, '
                  f'resolved = {resolved_value!r}', file=sys.stderr)

    if new_candidates:
        print(f'\n{len(new_candidates)} dependencies seen but not yet tracked '
              f'(rerun with --verbose to list them; add to solr-dependency-versions.json '
              f'if one becomes security-relevant).', file=sys.stderr)
        if args.verbose:
            for key in sorted(new_candidates):
                print(f'  {key}', file=sys.stderr)

    # Drift guard: every Solr version recorded in the dependency map must be in
    # solr-versions.txt, or expand_versions() will silently skip it when turning
    # a range into per-version purls.
    dep_map_versions = {v for per in dep_versions.values() for v in per}
    orphaned = sorted(dep_map_versions - set(all_versions), key=_version_key)
    if orphaned:
        print(f'\nERROR: {len(orphaned)} Solr version(s) appear in '
              f'{DEP_VERSIONS_FILE.name} but not in {VERSIONS_FILE.name} -- '
              f'expand_versions will not enumerate them: {", ".join(orphaned)}',
              file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
