name: Build a Pelican Website

on:
  push:
    branches: [ "main", "production", "github-actions" ]
  workflow_dispatch:

jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref == 'refs/heads/github-actions' && 'github-actions' || 'main' }}

      - name: Build Pelican Site
        uses: apache/infrastructure-actions/pelican@main
        with:
          destination: ${{ github.ref == 'refs/heads/github-actions' && 'pr-test' || 'asf-staging' }}
          gfm: 'false'
