name: Build Solr website with ASF Pelican action

on:
  push:
    branches: [ "main", "production" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'build.sh'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'
  workflow_dispatch:

jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          ref: ${{ github.ref == 'refs/heads/production' && 'production' || 'main' }}

      - name: Build Pelican Site
        uses: apache/infrastructure-actions/pelican@4deec7dce934d27491a0b1a8216f8d292548f7a4  # main 2025-04-13
        with:
          destination: ${{ github.ref == 'refs/heads/production' && 'asf-site' || 'asf-staging' }}
          gfm: 'false'
          version: '4.9.1'
          requirements: 'requirements.lock.txt'
