# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build Solr website with ASF Pelican action

on:
  push:
    branches: [ "main", "production" ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'build.sh'
      - '.editorconfig'
      - '.gitignore'
      - '.gitattributes'
  workflow_dispatch:

jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: ${{ github.ref == 'refs/heads/production' && 'production' || 'main' }}

      - name: Build Pelican Site
        uses: apache/infrastructure-actions/pelican@4deec7dce934d27491a0b1a8216f8d292548f7a4  # main 2025-04-13
        with:
          destination: ${{ github.ref == 'refs/heads/production' && 'asf-site' || 'asf-staging' }}
          gfm: 'false'
          version: '4.11.0.post0'
          requirements: 'requirements.txt'